name: 更新白名单文件

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行（即北京时间8点）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-whitelist:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: pip install -r requirements.txt
      
      - name: 执行脚本
        run: python main.py
      
      - name: 检查生成的文件
        run: |
          if [ ! -f dist/whitelist.hostrules ]; then
            echo "未能生成白名单文件"
            exit 1
          fi
          echo "白名单文件已生成，共有 $(wc -l < dist/whitelist.hostrules) 行"
      
      - name: 配置Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: 检出目标仓库
        uses: actions/checkout@v4
        with:
          repository: zphiliam/fsp-list
          path: fsp-list
          token: ${{ secrets.FSP_LIST_PAT }}
      
      - name: 更新目标仓库
        run: |
          cp dist/whitelist.hostrules fsp-list/
          cd fsp-list
          git add whitelist.hostrules
          
          if git diff --staged --quiet; then
            echo "文件没有变化，跳过提交"
          else
            git commit -m "auto update whitelist $(date +%Y-%m-%d)"
            git push
            echo "白名单已更新并推送到目标仓库"
          fi 